// <auto-generated />
namespace EC2Dash.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class EC2Instance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EC2Instance));
        
        string IMigrationMetadata.Id
        {
            get { return "201412041457279_EC2Instance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
