// <auto-generated />
namespace EC2Dash.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Group : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Group));
        
        string IMigrationMetadata.Id
        {
            get { return "201412032034544_Group"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
